# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18R8VpIslXWXrR5H3XmXv2nCDt-2kdTIx
"""

!pip install key-driver-analysis
!pip install statsmodels
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
import key_driver_analysis as kda
# Load dataset
df = pd.read_csv('/path/to/your/customer_satisfaction.csv')

# Display first few rows
df.head()
df = df.dropna()
target = 'SatisfactionScore'
features = df.columns[df.columns != target]
rw_df = kda.relative_importance(df, target=target, features=features, verbose=True)
print(rw_df)
X = df[features]
X = sm.add_constant(X)  # Adds a constant term to the predictor
y = df[target]

model = sm.OLS(y, X).fit()
print(model.summary())
from statsmodels.stats.outliers_influence import variance_inflation_factor

X_with_const = sm.add_constant(X)
vif_data = pd.DataFrame({
    "Feature": X_with_const.columns,
    "VIF": [variance_inflation_factor(X_with_const.values, i) for i in range(X_with_const.shape[1])]
})
print(vif_data)

